# This codemagic.yaml file includes a command to fix file permissions.
# This is the recommended solution if you cannot run git commands locally.

workflows:
  android-kotlin-app:
    name: Android Kotlin App Build
    instance_type: mac_mini_m2

    environment:
      # Specify the Java version for Gradle.
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          # This command makes the gradlew file executable.
          # It fixes the "Permission denied" error.
          chmod +x ./gradlew
          
      - name: Build Android App (Release with Debug Key)
        script: |
          # Now that gradlew is executable, this command will work.
          ./gradlew assembleRelease

    artifacts:
      - build/app/outputs/apk/release/*.apk
      - /tmp/codemagic_logs/*.log
