# This is the robust "copy" method adapted for a DEBUG build.
# It builds the debug APK and copies it to a known location before gathering artifacts.

workflows:
  android-kotlin-app-debug:
    name: Android Kotlin App Build (Debug)
    instance_type: mac_mini_m2

    environment:
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          chmod +x ./gradlew
          
      - name: Build Android App (Debug)
        script: |
          # Changed to 'assembleDebug' to build the debug variant.
          ./gradlew assembleDebug

      - name: Prepare APK for artifact collection
        script: |
          # Create a new directory at the top level named 'artifacts'
          mkdir -p $CM_BUILD_DIR/artifacts
          # Copy the generated DEBUG APK from its deep folder into our new 'artifacts' folder
          cp app/build/outputs/apk/debug/*.apk $CM_BUILD_DIR/artifacts/

    artifacts:
      # Now, we just collect everything from our simple, top-level 'artifacts' folder.
      - $CM_BUILD_DIR/artifacts/*.apk
      - /tmp/codemagic_logs/*.log
      
