# This is the final, optimized codemagic.yaml.
# It uses a precise artifact path based on the successful build log.

workflows:
  android-kotlin-app:
    name: Android Kotlin App Build
    instance_type: mac_mini_m2

    environment:
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          chmod +x ./gradlew
          
      - name: Build Android App (Release with Debug Key)
        script: |
          ./gradlew assembleRelease

    artifacts:
      # This path is now confirmed to be correct from your build log.
      - build/app/outputs/apk/release/*.apk
      - /tmp/codemagic_logs/*.log
