# This codemagic.yaml is configured to build the DEBUG version of the app.

workflows:
  android-kotlin-app-debug:
    name: Android Kotlin App Build (Debug)
    instance_type: mac_mini_m2

    environment:
      # Specify the Java version for Gradle.
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          chmod +x ./gradlew
          
      - name: Build Android App (Debug)
        script: |
          # The command is changed from 'assembleRelease' to 'assembleDebug'.
          ./gradlew assembleDebug

    artifacts:
      # The path is changed from 'release' to 'debug'.
      - build/app/outputs/apk/debug/*.apk
      - /tmp/codemagic_logs/*.log
