# codemagic.yaml using the system's installed Gradle instead of the wrapper.
# NOTE: This is not the recommended approach. Using the Gradle Wrapper (`gradlew`) is best practice.

workflows:
  android-kotlin-app:
    name: Android Kotlin App Build
    instance_type: mac_mini_m2

    environment:
      java: 17
      # You can specify a Gradle version here.
      # Codemagic will download and use this version.
      # It's best to match the version you use locally.
      gradle: 8.2

    triggering:
      events:
        - push

    scripts:
      - name: Build Android App (Release with Debug Key)
        script: |
          # This command uses the 'gradle' installed on the build machine,
          # not the './gradlew' wrapper from your project.
          gradle assembleRelease

    artifacts:
      - build/app/outputs/apk/release/*.apk
      - /tmp/codemagic_logs/*.log
      
