# This codemagic.yaml includes a debugging step to find the generated APK.

workflows:
  android-kotlin-app:
    name: Android Kotlin App Build
    instance_type: mac_mini_m2

    environment:
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          chmod +x ./gradlew
          
      - name: Build Android App (Release with Debug Key)
        script: |
          ./gradlew assembleRelease

      - name: List build outputs to find the APK
        script: |
          # This command will list all files in the build directory.
          # It will help us find the exact path of the generated .apk file.
          # The '|| true' ensures the build doesn't fail if the directory doesn't exist.
          find $CM_BUILD_DIR/build -type f || true
          find $CM_BUILD_DIR/app/build -type f || true


    artifacts:
      # This is a more aggressive glob pattern to find the APK anywhere in the build outputs.
      - build/**/outputs/apk/**/*.apk
      - /tmp/codemagic_logs/*.log
