# This is the final, most robust codemagic.yaml.
# It copies the final APK to a known location before gathering artifacts.

workflows:
  android-kotlin-app:
    name: Android Kotlin App Build
    instance_type: mac_mini_m2

    environment:
      java: 17

    triggering:
      events:
        - push

    scripts:
      - name: Add execute permission to gradlew
        script: |
          chmod +x ./gradlew
          
      - name: Build Android App (Release with Debug Key)
        script: |
          ./gradlew assembleRelease

      - name: Prepare APK for artifact collection
        script: |
          # Create a new directory at the top level named 'artifacts'
          mkdir -p $CM_BUILD_DIR/artifacts
          # Copy the generated APK from its deep folder into our new 'artifacts' folder
          cp app/build/outputs/apk/release/*.apk $CM_BUILD_DIR/artifacts/

    artifacts:
      # Now, we just collect everything from our simple, top-level 'artifacts' folder.
      - $CM_BUILD_DIR/artifacts/*.apk
      - /tmp/codemagic_logs/*.log
      
